name: Deploy dist

on:
  push:
    branches:
      master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Bootstrap
      uses: actions/setup-node@v1
      with:
        cmd: bootstrap
    - name: Spec tests
      uses: actions/setup-node@v1
      with:
          cmd: run run build:release
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
